# Generated by Django 4.2.2 on 2023-06-08 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='is_group',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
